[package]
name = "middleware_system"
version = "0.1.0"
edition = "2021"

[dependencies]
sol-trade-sdk = { path = "../.." }
solana-sdk = "2.3.0"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.79"